apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice-standalone
  labels:
    app: onlyoffice-standalone
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: onlyoffice-standalone
      labels:
        type: frontend
    spec:
      containers:
      - name: onlyoffice-standalone
        image: onlyoffice/4testing-documentserver-ee:7.4.0.173
---
apiVersion: v1
kind: Service
metadata:
  name: service-onlyoffice-standalone
spec:
  selector:
    app: onlyoffice-standalone
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
