apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: nginx
      labels:
        env: production
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.1
