apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replication
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: nginx
      labels:
        env: production
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3



